// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	controllers "news-hub-microservices_users-api/internal/controllers"

	mock "github.com/stretchr/testify/mock"
)

// ControllersFactory is an autogenerated mock type for the ControllersFactory type
type ControllersFactory struct {
	mock.Mock
}

// GetHealthChecksController provides a mock function with given fields:
func (_m *ControllersFactory) GetHealthChecksController() controllers.HealthChecksController {
	ret := _m.Called()

	var r0 controllers.HealthChecksController
	if rf, ok := ret.Get(0).(func() controllers.HealthChecksController); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(controllers.HealthChecksController)
		}
	}

	return r0
}

// GetUsersController provides a mock function with given fields:
func (_m *ControllersFactory) GetUsersController() controllers.UsersController {
	ret := _m.Called()

	var r0 controllers.UsersController
	if rf, ok := ret.Get(0).(func() controllers.UsersController); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(controllers.UsersController)
		}
	}

	return r0
}

type mockConstructorTestingTNewControllersFactory interface {
	mock.TestingT
	Cleanup(func())
}

// NewControllersFactory creates a new instance of ControllersFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewControllersFactory(t mockConstructorTestingTNewControllersFactory) *ControllersFactory {
	mock := &ControllersFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
