// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// UsersController is an autogenerated mock type for the UsersController type
type UsersController struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: context
func (_m *UsersController) Authenticate(context *gin.Context) {
	_m.Called(context)
}

// Create provides a mock function with given fields: context
func (_m *UsersController) Create(context *gin.Context) {
	_m.Called(context)
}

// Get provides a mock function with given fields: context
func (_m *UsersController) Get(context *gin.Context) {
	_m.Called(context)
}

type mockConstructorTestingTNewUsersController interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsersController creates a new instance of UsersController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsersController(t mockConstructorTestingTNewUsersController) *UsersController {
	mock := &UsersController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
