// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// RelationalDatabase is an autogenerated mock type for the RelationalDatabase type
type RelationalDatabase struct {
	mock.Mock
}

// DoMigration provides a mock function with given fields:
func (_m *RelationalDatabase) DoMigration() {
	_m.Called()
}

// Get provides a mock function with given fields:
func (_m *RelationalDatabase) Get() *gorm.DB {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

type mockConstructorTestingTNewRelationalDatabase interface {
	mock.TestingT
	Cleanup(func())
}

// NewRelationalDatabase creates a new instance of RelationalDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRelationalDatabase(t mockConstructorTestingTNewRelationalDatabase) *RelationalDatabase {
	mock := &RelationalDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
