// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ErrorWithMessage is an autogenerated mock type for the ErrorWithMessage type
type ErrorWithMessage struct {
	mock.Mock
}

// GetMessage provides a mock function with given fields:
func (_m *ErrorWithMessage) GetMessage() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewErrorWithMessage interface {
	mock.TestingT
	Cleanup(func())
}

// NewErrorWithMessage creates a new instance of ErrorWithMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewErrorWithMessage(t mockConstructorTestingTNewErrorWithMessage) *ErrorWithMessage {
	mock := &ErrorWithMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
