// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// HealthChecksController is an autogenerated mock type for the HealthChecksController type
type HealthChecksController struct {
	mock.Mock
}

// Ping provides a mock function with given fields: context
func (_m *HealthChecksController) Ping(context *gin.Context) {
	_m.Called(context)
}

type mockConstructorTestingTNewHealthChecksController interface {
	mock.TestingT
	Cleanup(func())
}

// NewHealthChecksController creates a new instance of HealthChecksController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHealthChecksController(t mockConstructorTestingTNewHealthChecksController) *HealthChecksController {
	mock := &HealthChecksController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
